### ISSUE TITLE
Allow the Kestra API schema in VSCode to be applied only to selected folder(s) e.g. the  "_flow" folder (rather than to all YAML files)

### ISSUE THREAD

**Issue by zd-dalibor** [kestra-io/vscode-kestra#18]
I try to fallow this note in the documentation to limit `kestra:/flow-schema.json` only to `_flows` folder in my workspace.
<img width="569" alt="image" src="https://github.com/kestra-io/vscode-kestra/assets/226822/9745a54f-432a-4292-85a1-e746f266a839">
But nothing is working.
I need to deinstall this extension because in my workspace I also have other types of json and yaml files.

Could someone geve some better explanation how to properly configure vscode and limit `kestra:/flow-schema.json` to be applied only to specific yaml files or specific folders and not to whole workspace.

**Comment by anna-geller** [comment]
thanks so much for reporting it, we will look into this soon

**Comment by anna-geller** [comment]
@brian-mulier-p, can you estimate whether this can be easily done or is a more complex issue?

**Comment by brian-mulier-p** [comment]
Looks easy but not sure when I'll be able to have a look

**Comment by Skraye** [comment]
Hi, you can now add a configuration in your `settings.json` that allows you to provide a regex to match for the schema to be apply: `kestra.schema.match-path`

For example, the following configuration : 
```json
"kestra.schema.match-path": "_flow"
```

will only match files that have "_flow" in their path

**Comment by anna-geller** [comment]
FYI: I extended the documentation a bit https://github.com/kestra-io/vscode-kestra/commit/fba7711b440b25ffe96d3a815c196f13b4664359
