### ISSUE TITLE
Set Kestra server in vscode settings

### ISSUE THREAD

**Issue by srichelle** [kestra-io/vscode-kestra#3]
Hello! 

The extension is nice and useful, but the process to connect to the server is not very practical.

You need to copy paste your server address  then your JWT token.
But as soon as you click outside VSCode, it considers the click as an input and go to the next input.
It's possible to manage and have the server address already copied before lauching the command, and then go get your JWT token as the second input is for basic auth.

It would be great to publish a setting in the VsCode Settings.json to store the server address at least.
Maybe we could also store the JWT token there and only ask for it if it's not set or inactive.

Publishing a new setting and using it is quite straightforward : 
https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

**Comment by Skraye** [comment]
Hello ! The issue may have been forgotten, but it has been done since a moment, you can know set up :
`kestra.api.url` in your settings.json (it will also be set up when configuring the instance for the first time)
