### ISSUE TITLE
Allow templating syntax

### ISSUE THREAD

**Issue by aballiet** [kestra-io/vscode-kestra#7]
Currently if we use some templating within YAML, VSCode extension / parser shows errrors : 

<img width="720" alt="image" src="https://github.com/kestra-io/vscode-kestra/assets/25565600/196775dc-3f64-46d4-8380-33cbd81186dc">

**Comment by anna-geller** [comment]
looks like this will be possible with the new TemplatedTask :) 

https://github.com/kestra-io/kestra/pull/3191
